version: '3'

volumes:
  deps:
  build:

services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    command:
      tail -f /dev/null
    # volumes:
    #   - .:/app
    #   - deps:/app/deps
    #   - build:/app/_build
    ports:
      - "4000:4000"
