version: '3'

volumes:
  deps:
  build:

services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    command:
      tail -f /dev/null
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
