version: '3'

volumes:
  deps:
  build:

services:
  blog:
    image: blog
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      tail -f /dev/null
    volumes:
      - .:/app
    ports:
      - "4000:4000"
